// <auto-generated />
using MASI_MarcoLegal.Server.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MASI_MarcoLegal.Server.Migrations
{
    [DbContext(typeof(MASIContext))]
    [Migration("20200826050604_ModeloInicial")]
    partial class ModeloInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Articulos", b =>
                {
                    b.Property<int>("ArticuloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CapituloID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticuloID");

                    b.HasIndex("CapituloID");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Capitulos", b =>
                {
                    b.Property<int>("CapituloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TituloID")
                        .HasColumnType("int");

                    b.HasKey("CapituloID");

                    b.HasIndex("TituloID");

                    b.ToTable("Capitulos");
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Considerandos", b =>
                {
                    b.Property<int>("ConsideranoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeyID")
                        .HasColumnType("int");

                    b.HasKey("ConsideranoID");

                    b.HasIndex("LeyID");

                    b.ToTable("Considerandos");
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Incisos", b =>
                {
                    b.Property<int>("IncisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticuloID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncisoID");

                    b.HasIndex("ArticuloID");

                    b.ToTable("Incisos");
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Leyes", b =>
                {
                    b.Property<int>("LeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeyID");

                    b.ToTable("Leyes");
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Titulos", b =>
                {
                    b.Property<int>("TituloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeyID")
                        .HasColumnType("int");

                    b.HasKey("TituloID");

                    b.HasIndex("LeyID");

                    b.ToTable("Titulos");
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Articulos", b =>
                {
                    b.HasOne("MASI_MarcoLegal.Server.Models.Capitulos", "Capitulo")
                        .WithMany("Articulos")
                        .HasForeignKey("CapituloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Capitulos", b =>
                {
                    b.HasOne("MASI_MarcoLegal.Server.Models.Titulos", "Titulo")
                        .WithMany("Capitulos")
                        .HasForeignKey("TituloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Considerandos", b =>
                {
                    b.HasOne("MASI_MarcoLegal.Server.Models.Leyes", "Ley")
                        .WithMany("Considerandos")
                        .HasForeignKey("LeyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Incisos", b =>
                {
                    b.HasOne("MASI_MarcoLegal.Server.Models.Articulos", "Articulo")
                        .WithMany("Incisos")
                        .HasForeignKey("ArticuloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MASI_MarcoLegal.Server.Models.Titulos", b =>
                {
                    b.HasOne("MASI_MarcoLegal.Server.Models.Leyes", "Ley")
                        .WithMany("Titulos")
                        .HasForeignKey("LeyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
